//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIAS_CONFIGURACIONCORREO
    {
        public string EMAIL { get; set; }
        public string CONTRASENA { get; set; }
        public string PUERTO { get; set; }
        public string HOST { get; set; }
    }
}
