//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GUIAS_RESERVADOS
    {
        public string ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<decimal> PAX { get; set; }
        public Nullable<System.DateTime> ENTRA { get; set; }
        public Nullable<System.DateTime> SALE { get; set; }
        public Nullable<long> ULTIMA_MODIFICACION { get; set; }
        public string ESTACION { get; set; }
    }
}
